# Define the compiler to use
CXX = g++

# Define the flags to pass to the compiler
CXXFLAGS = -Wall -Wextra -std=c++20

# Define the list of source files
SRCS =

# Define the name of the executable
TARGET = TITLE_PLACEHOLDER

# Default target: Build the executable
all: run

# Build target: build the program
build: $(TARGET)

# Run target: run the program
run: $(TARGET)
	./$(TARGET)

# Rule to build the executable
$(TARGET): $(SRCS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SRCS)

# Rule to clean the directory of build files
clean:
	rm -f $(TARGET)

.PHONY: all run clean
